### ISSUE TITLE
Torch 7 

### ISSUE THREAD

**Issue by weidongye** [soumith/convnet-benchmarks#109]
Hello,  

I am trying to run "th convnet-benchmarks/torch7/imagenet_winners" according to the readme

this command produces error: "~/torch/install/bin/luajit: ~/torch/install/share/lua/5.1/trepl/init.lua:384: module 'alexnet' not found:No LuaRocks module found for alexnet" 

I've followed the install instruction for the dependencies for torch7. Has anyone seen this before?

Thanks, 
Weidong

**Comment by soumith** [comment]
Run it from the imagenet_winners directory

**Comment by weidongye** [comment]
Thanks for the swift response Soumith!  That fixed my issue.

I try to run the fbnn implementation by commenting line 17 and uncommenting line 8 + 18, and it produced this error: "~/torch/install/share/lua/5.1/trepl/init.lua:384: module 'fb.torch.async_rng' not found:No LuaRocks module found for fb.torch.async_rng" 

I have install all the pre-req library, and you provide some advice please?

Thanks,
Weidong

**Comment by soumith** [comment]
fbnn is a bit redundant now, just use cudnn and forget fbnn stuff ever existed, all fft stuff is available in cudnn now.

**Comment by fqnchina** [comment]
Hi soumith, 

Could you explain this a bit more? What you mean by all fft stuff is in cudnn now. From the latest cudnn document, I didn't see they mention fft is implemented already in cudnn.

**Comment by soumith** [comment]
Search for FFT in the CuDNN Manual, you will find it.
https://github.com/soumith/cudnn.torch/blob/master/ffi.lua#L395-L403
