### ISSUE TITLE
Use Tensorflow benchmark without GPU

### ISSUE THREAD

**Issue by sjlee7748** [soumith/convnet-benchmarks#116]
Hi, All

I want to use Tensorflow benchmark without GPU.
When I use your source code(benchmark_googlenet.py), errors exist as below.

Command: `python benchmark_googlenet.py`
Error: `W tensorflow/core/framework/op_kernel.cc:940] Invalid argument: shape must be a vector of {int32,int64}.
terminate called after throwing an instance of 'std::system_error'
  what():  Operation not permitted
Aborted (core dumped)
`

If someone know the method about using this benchmark without GPU, please tell me about that.
Thank you so much.

**Comment by xzy256** [comment]
@sjlee7748  how to you resolve the situation without GPU?
