### ISSUE TITLE
fbcunn overfeat and vgg fail

### ISSUE THREAD

**Issue by nallezard** [soumith/convnet-benchmarks#42]
overfeat and vgg benchmark fail with fbcunn kernel on a titan black card.
Even if i reduce the batch size the benchmark run longer but i still get this (for overfeat)
Running on device: GeForce GTX TITAN Black	
ModelType: OverFeat[fast]	Kernels: fbfft	Input shape: 128x3x231x231	
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0430 14:30:32.984395 32763 SpatialConvolutionCuFFTTuner.cpp:117] START exploring FFT perf for pass = updateOutput     (b x p x f) = 128x96x256 (input rows x cols) = 28x28 (filter rows x cols) = 5x5 (common rows x cols) = 28x28 
I0430 14:30:35.358149 32763 SpatialConvolutionCuFFTTuner.cpp:122] Found best result   Buffer=921.31M strategy = (Many) (b x p x f) = 128x96x256 (input rows x cols) = 28x28 (filter rows x cols) = 5x5 (common rows x cols) = 28x28  GReductions(virtual fmas)/s = 3021.61  time = 20.41ms
I0430 14:30:35.358180 32763 SpatialConvolutionCuFFTTuner.cpp:117] START exploring FFT perf for pass = updateGradInput  (b x p x f) = 128x96x256 (input rows x cols) = 28x28 (filter rows x cols) = 5x5 (common rows x cols) = 28x28 
I0430 14:30:37.495909 32763 SpatialConvolutionCuFFTTuner.cpp:122] Found best result   Buffer=921.31M strategy = (Many) (b x p x f) = 128x96x256 (input rows x cols) = 28x28 (filter rows x cols) = 5x5 (common rows x cols) = 28x28  GReductions(virtual fmas)/s = 3157.00  time = 19.53ms
I0430 14:30:37.495929 32763 SpatialConvolutionCuFFTTuner.cpp:117] START exploring FFT perf for pass = accGradParameters(b x p x f) = 128x96x256 (input rows x cols) = 28x28 (filter rows x cols) = 5x5 (common rows x cols) = 28x28 
I0430 14:30:39.731259 32763 SpatialConvolutionCuFFTTuner.cpp:122] Found best result   Buffer=1047.13M strategy = (Many) (b x p x f) = 128x96x256 (input rows x cols) = 28x28 (filter rows x cols) = 5x5 (common rows x cols) = 28x32  GReductions(virtual fmas)/s = 2990.89  time = 20.61ms
I0430 14:30:39.738314 32763 SpatialConvolutionCuFFTTuner.cpp:117] START exploring FFT perf for pass = updateOutput     (b x p x f) = 128x256x512 (input rows x cols) = 14x14 (filter rows x cols) = 3x3 (common rows x cols) = 14x14 
I0430 14:30:42.112609 32763 SpatialConvolutionCuFFTTuner.cpp:122] Found best result   Buffer=798.49M strategy = (Many) (b x p x f) = 128x256x512 (input rows x cols) = 14x14 (filter rows x cols) = 3x3 (common rows x cols) = 14x14  GReductions(virtual fmas)/s = 1716.03  time = 17.25ms
I0430 14:30:42.112627 32763 SpatialConvolutionCuFFTTuner.cpp:117] START exploring FFT perf for pass = updateGradInput  (b x p x f) = 128x256x512 (input rows x cols) = 14x14 (filter rows x cols) = 3x3 (common rows x cols) = 14x14 
I0430 14:30:44.346437 32763 SpatialConvolutionCuFFTTuner.cpp:122] Found best result   Buffer=797.44M strategy = (Many) (b x p x f) = 128x256x512 (input rows x cols) = 14x14 (filter rows x cols) = 3x3 (common rows x cols) = 14x14  GReductions(virtual fmas)/s = 1881.80  time = 15.73ms
I0430 14:30:44.346457 32763 SpatialConvolutionCuFFTTuner.cpp:117] START exploring FFT perf for pass = accGradParameters(b x p x f) = 128x256x512 (input rows x cols) = 14x14 (filter rows x cols) = 3x3 (common rows x cols) = 14x14 
I0430 14:30:46.663117 32763 SpatialConvolutionCuFFTTuner.cpp:122] Found best result   Buffer=797.44M strategy = (Many) (b x p x f) = 128x256x512 (input rows x cols) = 14x14 (filter rows x cols) = 3x3 (common rows x cols) = 14x14  GReductions(virtual fmas)/s = 1732.12  time = 17.09ms
I0430 14:30:46.668112 32763 SpatialConvolutionCuFFTTuner.cpp:117] START exploring FFT perf for pass = updateOutput     (b x p x f) = 128x512x1024 (input rows x cols) = 14x14 (filter rows x cols) = 3x3 (common rows x cols) = 14x14 
I0430 14:30:47.615033 32763 SpatialConvolutionCuFFTTuner.cpp:99] std::bad_alloc
I0430 14:30:47.615075 32763 SpatialConvolutionCuFFTTuner.cpp:122] Found best result   Buffer=1963.54M strategy = (Batch) (b x p x f) = 128x512x1024 (input rows x cols) = 14x14 (filter rows x cols) = 3x3 (common rows x cols) = 14x14  GReductions(virtual fmas)/s = 1559.80  time = 75.89ms
I0430 14:30:47.615084 32763 SpatialConvolutionCuFFTTuner.cpp:117] START exploring FFT perf for pass = updateGradInput  (b x p x f) = 128x512x1024 (input rows x cols) = 14x14 (filter rows x cols) = 3x3 (common rows x cols) = 14x14 
I0430 14:30:54.954167 32763 SpatialConvolutionCuFFTTuner.cpp:122] Found best result   Buffer=2531.26M strategy = (Batch) (b x p x f) = 128x512x1024 (input rows x cols) = 14x14 (filter rows x cols) = 3x3 (common rows x cols) = 14x14  GReductions(virtual fmas)/s = 2655.10  time = 44.59ms
I0430 14:30:54.954197 32763 SpatialConvolutionCuFFTTuner.cpp:117] START exploring FFT perf for pass = accGradParameters(b x p x f) = 128x512x1024 (input rows x cols) = 14x14 (filter rows x cols) = 3x3 (common rows x cols) = 14x14 
I0430 14:31:02.475479 32763 SpatialConvolutionCuFFTTuner.cpp:122] Found best result   Buffer=2504.00M strategy = (Many) (b x p x f) = 128x512x1024 (input rows x cols) = 14x14 (filter rows x cols) = 3x3 (common rows x cols) = 14x14  GReductions(virtual fmas)/s = 2141.34  time = 55.28ms
/home/allezard/torch/install/bin/luajit: /home/allezard/torch/extra/cutorch/lib/THC/THCStorage.c(112) : cuda runtime error : invalid device pointer
Segmentation fault (core dumped)

Does anyone have seen this before it?
Is it possible to run the test on a titan black?
Thanks

**Comment by soumith** [comment]
fbcunn's FFT modules need 12GB for Overfeat/VGG. We have some upcoming work that gives a flexibility of choosing mem usage vs performance (using Tiling FFT). Stay tuned, we will hopefully release it before our talk at ICLR on May 8th.
