### ISSUE TITLE
Out of memory error for torch7/imagenet_winners

### ISSUE THREAD

**Issue by pgera** [soumith/convnet-benchmarks#45]
Hi,
I'm seeing an out of memory error with torch7/imagenet_winners on a titan-x for "VGG Model-A  Kernels: fbfft ". All the dependencies are up to date. 

stdout:
Running on device: Graphics Device
ModelType: AlexNet      Kernels: cudnn  Input shape: 128x3x224x224
cudnn                                   :updateOutput():      69.61
cudnn                                :updateGradInput():      83.50
cudnn                              :accGradParameters():      79.05
cudnn                                          :Forward:      69.61
cudnn                                         :Backward:     162.55
cudnn                                            :TOTAL:     232.16
ModelType: AlexNet      Kernels: nn     Input shape: 128x3x224x224
nn                                      :updateOutput():     139.52
nn                                   :updateGradInput():     116.48
nn                                 :accGradParameters():     101.57
nn                                             :Forward:     139.52
nn                                            :Backward:     218.05
nn                                               :TOTAL:     357.57
ModelType: AlexNet      Kernels: fbfft  Input shape: 128x3x224x224
fbfft                                   :updateOutput():      44.87
fbfft                                :updateGradInput():      46.73
fbfft                              :accGradParameters():      44.20
fbfft                                          :Forward:      44.87
fbfft                                         :Backward:      90.93
fbfft                                            :TOTAL:     135.79
ModelType: VGG Model-A  Kernels: cudnn  Input shape: 64x3x224x224
cudnn                                   :updateOutput():     339.59
cudnn                                :updateGradInput():     399.12
cudnn                              :accGradParameters():     352.86
cudnn                                          :Forward:     339.59
cudnn                                         :Backward:     751.98
cudnn                                            :TOTAL:    1091.57
ModelType: VGG Model-A  Kernels: nn     Input shape: 64x3x224x224
nn                                      :updateOutput():     348.41
nn                                   :updateGradInput():     381.35
nn                                 :accGradParameters():     372.84
nn                                             :Forward:     348.41
nn                                            :Backward:     754.19
nn                                               :TOTAL:    1102.61
ModelType: VGG Model-A  Kernels: fbfft  Input shape: 64x3x224x224

stderr:
http://pastebin.com/NaCCgzt9

I'm just getting started with this suite and have very little experience with the environment. Any help would be appreciated.

**Comment by soumith** [comment]
@pgera a new push to fbcunn should come before August 15th, and they have proper fallbacks (to cudnn) on out-of-memory etc. will keep you posted.
