### ISSUE TITLE
Pre-trained Models?

### ISSUE THREAD

**Issue by bluemellophone** [soumith/convnet-benchmarks#48]
I have been trying to get my hands on a pre-trained OverFeat caffenet model file.  Anybody willing to share?  I've found some prototxt's around, but (unsurprisingly) never the actual caffemodel.

**Comment by soumith** [comment]
fwiw, the weights that the overfeat guys released are a binary file, and the format is pretty well known:
https://github.com/jhjin/overfeat-torch/blob/master/run.lua#L61-L77

If you are feeling adventurous, you can do some C++ to do the same in Caffe.
I guess this issue should also be opened in https://github.com/BVLC/caffe where all the caffe users will see it.
