### ISSUE TITLE
Is the time for per image or a batch of images?

### ISSUE THREAD

**Issue by sunshineatnoon** [soumith/convnet-benchmarks#53]
Thanks for your awesome work!
I am a little confused about the benchmarks you got, is the time in the tables for a single image or for a batch of images? I looked into imagenet_winners folder and found that for the first three nets, the batch size is 128(if I understand correctly), but for the vgg net the batch size is 64, so when you get your results, did you divided that time by the batch size?

**Comment by soumith** [comment]
The time is for the full batch.
