### ISSUE TITLE
Can't reproduce timings on NVIDIA Titan-X

### ISSUE THREAD

**Issue by ozabluda** [soumith/convnet-benchmarks#57]
My benchmark timings on NVIDIA Titan-X (libcudnn.so.7.0.64) are much slower than those of Soumith. My Titan-X is stock from NVIDIA, modestly overclocked (250 Mhz) and overvolted (.05mV) (see below for the guide). Anybody has any ideas why? Do I need to flash a custom BIOS?

user@dnn1:~/convnet-benchmarks/torch7/imagenet_winners$ th benchmark.lua
Running on device: GeForce GTX TITAN X
ModelType: AlexNet      Kernels: cudnn  Input shape: 128x3x224x224
cudnn                                   :updateOutput():      41.66
cudnn                                :updateGradInput():      62.85
cudnn                              :accGradParameters():      59.55
cudnn                                          :Forward:      41.66
cudnn                                         :Backward:     122.41
cudnn                                            :TOTAL:     164.07
ModelType: OverFeat[fast]       Kernels: cudnn  Input shape: 128x3x231x231
cudnn                                   :updateOutput():     136.36
cudnn                                :updateGradInput():     251.24
cudnn                              :accGradParameters():     209.67
cudnn                                          :Forward:     136.36
cudnn                                         :Backward:     460.91
cudnn                                            :TOTAL:     597.27
ModelType: VGG Model-A  Kernels: cudnn  Input shape: 64x3x224x224
cudnn                                   :updateOutput():     248.66
cudnn                                :updateGradInput():     338.22
cudnn                              :accGradParameters():     272.91
cudnn                                          :Forward:     248.66
cudnn                                         :Backward:     611.13
cudnn                                            :TOTAL:     859.79
ModelType: GoogleNet    Kernels: cudnn  Input shape: 128x3x224x224
cudnn                                   :updateOutput():     120.70
cudnn                                :updateGradInput():     210.48
cudnn                              :accGradParameters():     141.56
cudnn                                          :Forward:     120.70
cudnn                                         :Backward:     352.04
cudnn                                            :TOTAL:     472.74

==============

./build/tools/caffe time --model convnet-benchmarks/caffe/imagenet_winners/alexnet.prototxt -gpu=0 --iterations=10
I0923 15:29:33.813731  4276 caffe.cpp:354] Average time per layer: 
I0923 15:29:33.813736  4276 caffe.cpp:357]      conv1   forward: 7.28601 ms.
I0923 15:29:33.813745  4276 caffe.cpp:360]      conv1   backward: 16.4974 ms.
I0923 15:29:33.813751  4276 caffe.cpp:357] conv1/relu   forward: 0.802221 ms.
I0923 15:29:33.813758  4276 caffe.cpp:360] conv1/relu   backward: 1.17941 ms.
I0923 15:29:33.813765  4276 caffe.cpp:357] pool1/3x3_s2 forward: 0.540144 ms.
I0923 15:29:33.813771  4276 caffe.cpp:360] pool1/3x3_s2 backward: 2.35192 ms.
I0923 15:29:33.813776  4276 caffe.cpp:357] conv2/5x5_s1 forward: 9.20351 ms.
I0923 15:29:33.813782  4276 caffe.cpp:360] conv2/5x5_s1 backward: 32.1066 ms.
I0923 15:29:33.813789  4276 caffe.cpp:357] cpnv2/relu   forward: 0.563315 ms.
I0923 15:29:33.813796  4276 caffe.cpp:360] cpnv2/relu   backward: 0.836832 ms.
I0923 15:29:33.813802  4276 caffe.cpp:357] pool2/3x3_s2 forward: 0.38049 ms.
I0923 15:29:33.813807  4276 caffe.cpp:360] pool2/3x3_s2 backward: 1.83551 ms.
I0923 15:29:33.813813  4276 caffe.cpp:357] conv3/3x3_s1 forward: 4.51088 ms.
I0923 15:29:33.813819  4276 caffe.cpp:360] conv3/3x3_s1 backward: 18.8913 ms.
I0923 15:29:33.813825  4276 caffe.cpp:357] conv3/relu   forward: 0.275491 ms.
I0923 15:29:33.813832  4276 caffe.cpp:360] conv3/relu   backward: 0.412963 ms.
I0923 15:29:33.813838  4276 caffe.cpp:357] conv4/3x3_s1 forward: 5.82792 ms.
I0923 15:29:33.813844  4276 caffe.cpp:360] conv4/3x3_s1 backward: 23.6848 ms.
I0923 15:29:33.813850  4276 caffe.cpp:357] conv4/relu   forward: 0.185322 ms.
I0923 15:29:33.813856  4276 caffe.cpp:360] conv4/relu   backward: 0.277126 ms.
I0923 15:29:33.813863  4276 caffe.cpp:357] conv5/3x3_s1 forward: 4.08288 ms.
I0923 15:29:33.813868  4276 caffe.cpp:360] conv5/3x3_s1 backward: 15.7675 ms.
I0923 15:29:33.813874  4276 caffe.cpp:357] conv5/relu   forward: 0.189014 ms.
I0923 15:29:33.813880  4276 caffe.cpp:360] conv5/relu   backward: 0.280253 ms.
I0923 15:29:33.813886  4276 caffe.cpp:357] pool5/3x3_s2 forward: 0.12167 ms.
I0923 15:29:33.813892  4276 caffe.cpp:360] pool5/3x3_s2 backward: 0.681011 ms.
I0923 15:29:33.813899  4276 caffe.cpp:357]        fc6   forward: 2.85131 ms.
I0923 15:29:33.813905  4276 caffe.cpp:360]        fc6   backward: 3.13384 ms.
I0923 15:29:33.813911  4276 caffe.cpp:357]        fc7   forward: 0.799648 ms.
I0923 15:29:33.813917  4276 caffe.cpp:360]        fc7   backward: 1.42024 ms.
I0923 15:29:33.813923  4276 caffe.cpp:357]        fc8   forward: 0.46623 ms.
I0923 15:29:33.813930  4276 caffe.cpp:360]        fc8   backward: 0.492112 ms.
I0923 15:29:33.813942  4276 caffe.cpp:365] Average Forward pass: 38.1855 ms.
I0923 15:29:33.813948  4276 caffe.cpp:367] Average Backward pass: 119.916 ms.
I0923 15:29:33.813954  4276 caffe.cpp:369] Average Forward-Backward: 158.163 ms.

==============

user@dnn1:~$ nvidia-smi -q -d TEMPERATURE,POWER,CLOCK,PERFORMANCE

==============NVSMI LOG==============

Timestamp                           : Wed Sep 23 15:23:32 2015
Driver Version                      : 346.82

Attached GPUs                       : 1
GPU 0000:01:00.0
    Performance State               : P0
    Clocks Throttle Reasons
        Idle                        : Not Active
        Applications Clocks Setting : Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
        Unknown                     : Not Active
    Temperature
        GPU Current Temp            : 52 C
        GPU Shutdown Temp           : 97 C
        GPU Slowdown Temp           : 92 C
    Power Readings
        Power Management            : Supported
        Power Draw                  : 279.96 W
        Power Limit                 : 250.00 W
        Default Power Limit         : 250.00 W
        Enforced Power Limit        : 250.00 W
        Min Power Limit             : 150.00 W
        Max Power Limit             : 275.00 W
    Clocks
        Graphics                    : 1427 MHz
        SM                          : 1427 MHz
        Memory                      : 3505 MHz
    Applications Clocks
        Graphics                    : 1392 MHz
        Memory                      : 3505 MHz
    Default Applications Clocks
        Graphics                    : 999 MHz
        Memory                      : 3505 MHz
    Max Clocks
        Graphics                    : 1642 MHz
        SM                          : 1642 MHz
        Memory                      : 3505 MHz
    SM Clock Samples
        Duration                    : 29.80 sec
        Number of Samples           : 100
        Max                         : 1465 MHz
        Min                         : 1253 MHz
        Avg                         : 1423 MHz
    Memory Clock Samples
        Duration                    : 29.80 sec
        Number of Samples           : 100
        Max                         : 3505 MHz
        Min                         : 3505 MHz
        Avg                         : 3505 MHz
    Clock Policy
        Auto Boost                  : On
        Auto Boost Default          : On

=========

user@dnn1:~$ cat ~/overclock.sh
sudo nvidia-smi -i 0 -pm 1 
sudo nvidia-smi -i 0 -ac 3505,1392
DISPLAY=:0 nvidia-settings -a [gpu:0]/GPUPowerMizerMode=1
DISPLAY=:0 nvidia-settings -a [gpu:0]/GPUOverVoltageOffset=50000

#from nvidia-settings GUI (can’t do it from command-line) set “Graphics clock Offset” to 300 Mhz, “Memory Transfer Rate Offset” to 800

**Comment by soumith** [comment]
@ozabluda those timings look like they are of cudnn R2, or cudnn R3 with R2 bindings.

To make sure everything is kosher, can you do the following and report the output here:

```
th -lcudnn -e "print(cudnn.version)"
```

it should be greater than 3000 (which is the R3 version of cudnn).

Also, make sure you are using the latest master branch of cudnn.torch: 

```
git clone https://github.com/soumith/cudnn.torch
cd cudnn.torch
luarocks make
```

I checked that the numbers are in the same range of things on:
- NVIDIA Digits box (4x Titan X)
- NVIDIA M6000
- Another box of mine which has 1x Titan-X

If you still cant reproduce, I can give ssh access to one of my boxes which I reproduced the numbers.

**Comment by ozabluda** [comment]
user@dnn1:~/convnet-benchmarks/torch7/imagenet_winners$ th -lcudnn -e "print(cudnn.version)"
3007

after updating to the latest master branch of cudnn.torch, as described above, my timings are actually 10-25% faster than yours (all that overclocking paid off :-). Thank you. I will report on Caffe/cudnn-v3 in another post.

user@dnn1:~/convnet-benchmarks/torch7/imagenet_winners$ th benchmark.lua 
Running on device: GeForce GTX TITAN X  
ModelType: AlexNet      Kernels: cudnn  Input shape: 128x3x224x224
cudnn                                   :updateOutput():      29.65
cudnn                                :updateGradInput():      28.08
cudnn                              :accGradParameters():      29.85
cudnn                                          :Forward:      29.65
cudnn                                         :Backward:      57.93
cudnn                                            :TOTAL:      87.58
ModelType: OverFeat[fast]       Kernels: cudnn  Input shape: 128x3x231x231
cudnn                                   :updateOutput():     103.65
cudnn                                :updateGradInput():      91.89
cudnn                              :accGradParameters():     101.63
cudnn                                          :Forward:     103.65
cudnn                                         :Backward:     193.52
cudnn                                            :TOTAL:     297.17
ModelType: VGG Model-A  Kernels: cudnn  Input shape: 64x3x224x224
cudnn                                   :updateOutput():     180.06
cudnn                                :updateGradInput():     192.06
cudnn                              :accGradParameters():     184.81
cudnn                                          :Forward:     180.06
cudnn                                         :Backward:     376.87
cudnn                                            :TOTAL:     556.94
ModelType: GoogleNet    Kernels: cudnn  Input shape: 128x3x224x224
cudnn                                   :updateOutput():      96.69
cudnn                                :updateGradInput():     156.27
cudnn                              :accGradParameters():      85.10
cudnn                                          :Forward:      96.69
cudnn                                         :Backward:     241.37
cudnn                                            :TOTAL:     338.06
