### ISSUE TITLE
Benchmark tensorflow

### ISSUE THREAD

**Issue by cancan101** [soumith/convnet-benchmarks#65]
Once there are examples of standard networks running on [tensorflow](http://tensorflow.org/).

**Comment by soumith** [comment]
Thanks. On it right away!

**Comment by benanne** [comment]
It seems to only support CuDNN v2, so I'm curious to see if it manages to be competitive.

**Comment by Jokeren** [comment]
Very curious about its performance, as Jeff Dean hasn't mentioned much about its speed.

**Comment by adamist521** [comment]
Would this be same condition?
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/image/alexnet/alexnet_benchmark.py


Done experiment on Tesla K-80 and showed around 180ms forward and 540ms forward-backward.

![2015-11-11 15 21 21](https://cloud.githubusercontent.com/assets/2974951/11085313/1755ad7a-8888-11e5-98bc-f97f44d4b479.png)

![2015-11-11 15 20 34](https://cloud.githubusercontent.com/assets/2974951/11085300/f9bb4360-8887-11e5-8d8f-376f4837098d.png)

**Comment by soumith** [comment]
@adamist521 That benchmark is incomplete. It does not have FC layers, loss is different etc. 
I should have numbers in about 1-2 hours. Finished AlexNet, Overfeat, working on VGG, Googlenet. Stay tuned.

**Comment by adamist521** [comment]
@soumith Awesome!

**Comment by bhack** [comment]
:+1:

**Comment by bhack** [comment]
@soumith take a look at https://github.com/tensorflow/tensorflow/pull/113

**Comment by soumith** [comment]
closing this. discuss here: https://github.com/soumith/convnet-benchmarks/issues/66
