### ISSUE TITLE
OpenCL benchmarks are not fair

### ISSUE THREAD

**Issue by 222464** [soumith/convnet-benchmarks#69]
As far as I can tell, the OpenCL based benchmarks are also done on the Nvidia GPU. Nvidia purposely nerfed their OpenCL drivers to promote CUDA (AMD is on OpenCL 2.0 and Nvidia is on 1.1, and then are not equal in performance).

Non-machine learning benchmarks show more or less performance parity, when OpenCL is run on a AMD GPU of similar capabilities.

So as it is right now, I would say the OpenCL results are extremely misleading.

**Comment by soumith** [comment]
@222464 folks at AMD, including @gujunli said that they are working on benchmarks on AMD cards. I dont have a machine with an AMD card.

**Comment by soumith** [comment]
fwiw, I clearly state my hardware, so there's no misrepresentation.

**Comment by hughperkins** [comment]
> As far as I can tell, the OpenCL based benchmarks are also done on the Nvidia GPU. Nvidia purposely nerfed their OpenCL drivers to promote CUDA (AMD is on OpenCL 2.0 and Nvidia is on 1.1, and then are not equal in performance).

Well... yes and no.  I've run my own code on AMD gpus, and the results were ... well... anyway... AMD has forked Soumith's benchmarks at https://github.com/amd/convnet-benchmarks , so you could push them to publish some results I guess :-)  The scripts that soumith uses are all opensource, publically available, so anyone can run them against any GPU they want, and publish the results.

**Comment by scott-gray** [comment]
Keep in mind that my kernels are not written in cuda-c.  AMD has very graciously posted their complete ISA here: http://amd-dev.wpengine.netdna-cdn.com/wordpress/media/2013/07/AMD_GCN3_Instruction_Set_Architecture.pdf

So if you really want to compare hardware to hardware that's now achievable.  I personally don't think it's possible to efficiently implement these dense linear algebra kernels in a higher level language.  That's particularly true of my new winograd kernels which require an incredibly well crafted register budget along with very carefully scheduled instructions.

**Comment by 222464** [comment]
Thanks for the responses. Yes, it's fine that you stated the hardware, but I just felt like many people draw the wrong conclusions. I used both CUDA and OpenCL, I found them to be about the same speed for similar hardware. Adobe products also have comparisons of the two, which show that they are about the same. The only comparison that can be made is really cross-hardware I am afraid.

Thank you!

**Comment by hughperkins** [comment]
Hi 222464, I'm interested in the benchmarking you tried, however informal.
- what library(s) did you use?
- what cards?
- what benchmarking test(s)?
- what were the results?
