### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ETRI-cloud** [soumith/convnet-benchmarks#72]
Hi, I'm new to this deep learning.
I have a few newbie questions. 
For benchmark, you have AlexNet, Overfeat, OxfordNet, GoogleNet., etc. These are models.
And also in each model category, there are libraries and classes. So how did you test them?
What I mean by this is for Overfeat, which is written in c++ and such has its own way to compile and run. To test benchmarks of Overfeat using different libraries such as torch, tensorflow, caffe., etc, did you simply rewrite the code in the given library? Or is there some kind of linker program(e.g. something that maps tensorflow and Alexnet)?
I know this is a very basic question. Thank you so much for your help!

**Comment by hughperkins** [comment]
This is not my repo, I'm not affiliated with it, and I reckon such questions are best in the forums, eg the torch forums https://groups.google.com/forum/#!forum/torch7 but...

Each model is essentially a network design, like 'First layer is 32 5x5 convolutional filters, then a max pooling with stride 2, and pooling size, and then ... (etc...)'.

Such a network design is implementation-independent.  The code supplied with papers is one particular instantiation of the model, but many models can typically be instantiated using any of many possible libraries, eg torch, caffe, theano, mxnet, ...

And so, in the benchmarks, each model is instantiated for that library.  You can see the instantiations in the relevant sub-directory, eg for caffe, they are in https://github.com/soumith/convnet-benchmarks/tree/master/caffe  tensorflow is at https://github.com/soumith/convnet-benchmarks/tree/master/tensorflow , etc ...

**Comment by ETRI-cloud** [comment]
Thank you ! :)
