### ISSUE TITLE
Running Torch benchmark with cuDNN

### ISSUE THREAD

**Issue by Alexey-Kamenev** [soumith/convnet-benchmarks#74]
I'm having a problem running torch benchmark, I'm getting CUDNN_STATUS_NOT_SUPPORTED.
I followed the instructions and installed all required dependencies and Torch works fine on simple (non-convolutional) nets. Here is the output:

`
alexeyk@gcrgpu1071:~/convnet-benchmarks/torch7/imagenet_winners$ th benchmark.lua
Running on device: Tesla K40m
ModelType: AlexNet      Kernels: cudnn  Input shape: 128x3x224x224
/var/storage/shared/ipgsp/sys/jobs/application_1447977864059_0183/torch/install/bin/luajit: ...77864059_0183/torch/install/share/lua/5.1/cudnn/init.lua:58: Error in CuDNN: CUDNN_STATUS_NOT_SUPPORTED
stack traceback:
        [C]: in function 'error'
        ...77864059_0183/torch/install/share/lua/5.1/cudnn/init.lua:58: in function 'errcheck'
        ...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:385: in function 'updateOutput'
        ...64059_0183/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'updateOutput'
        ...64059_0183/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'updateOutput'
        benchmark.lua:55: in main chunk
        [C]: in function 'dofile'
        ...0183/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670
`
Any ideas what I might be doing wrong?

**Comment by soumith** [comment]
Hey Alexey, the CUDNN error messages are quite cryptic. Do you have the latest CuDNN, and CUDA 7.0 or above, as well as an NVIDIA driver of 352.xx or more...

**Comment by Alexey-Kamenev** [comment]
Hi Soumith,
I have cuDNN v2, v3 as well as v4 on that machine, how to tell Torch which one to use (and how to determine which one it actually uses)?
As for the drivers: according to nvidia-smi, I have  346.72, however, other toolkits that use cuDNN (versions from v2 to v4) are working fine.
I can certainly update the drivers but I thought it might be related to Torch not able to find the correct version?
Thanks.

**Comment by soumith** [comment]
@Alexey-Kamenev let's discuss here: https://github.com/soumith/cudnn.torch/issues/75
