### ISSUE TITLE
On Chainer results

### ISSUE THREAD

**Issue by beam2d** [soumith/convnet-benchmarks#77]
Thank you for adding Chainer results to the tables! I am surprised at the result superior to that of Caffe native, since the implementation of Convolution2D in Chainer is basically same as that of Caffe. Then I hypothesize that the Chainer's results are measured on environment with cuDNN installed, in which case Chainer automatically detects it and switch the implementation to use it. If so, could you add a note indicating that cuDNN is enabled, to avoid confusion? (If this hypothesis is wrong, then ignore this message).

**Comment by soumith** [comment]
It is indeed the case. I just added a note to the main README to reflect this:
https://github.com/soumith/convnet-benchmarks/blob/master/README.md#one-small-note

**Comment by beam2d** [comment]
Thank you very much!
