### ISSUE TITLE
A quick question about set up

### ISSUE THREAD

**Issue by Botev** [soumith/convnet-benchmarks#79]
Hi,
Since I recently wanted to do something similar on RNNs I wanted to ask you, what exactly is your set up for benchmarking? E.g. how many runs, tests do you do, how long you let them warm up(brunout period) and similar details? Also on Nvidia how did you measure the memory usage? All I get from the `nvidia-smi` is memory utilization in %? Otherwise for instance Theano sometimes preallocates almost all of the memory so Memory Usage shows like almost all of the 12GB, while the utilization is as low as 30%. Any other details you would share would be great!

**Comment by soumith** [comment]
Usually, I warm up the GPU by running the benchmarks a hundred times-ish (depends on which one and how long it is).
I get memory utilization from nvidia-smi in MB, such as: 927MiB / 12284MiB
I've also tried ever increasing batch sizes to find the breaking point where things go out of memory. 
GPU-Utilization varies between framework to framework, I dont really look at it much.

**Comment by Botev** [comment]
Hmm, that is interesting. For TensorFlow this does not seem to work as it seems they allocate all of the free memory beforehead. For instance I get `11729MiB / 12287MiB` in-respectable of the size of the model I run. Have you tried Tf by any chance and got sensible result?

**Comment by soumith** [comment]
@Botev for TensorFlow, it maintains it pre-allocs and then manages it's own memory, ever-increasing batch sizes are your best bet. TF probably has some debugging tools for memory tracking, I just dont know enough about it.
