### ISSUE TITLE
HcCaffe

### ISSUE THREAD

**Issue by bhack** [soumith/convnet-benchmarks#81]
It could be interesting to benchmark this new effort: http://gpuopen.com/compute-product/hccaffe/

**Comment by soumith** [comment]
that looks very interesting. I'll have to get my hands on one of those Fiji cards first.

**Comment by bhack** [comment]
@soumith I think you can get a partnership of your benchmark with @michaellarabel of phoronix. He has a plenty of hardware.

**Comment by michaellarabel** [comment]
Is there any complete script anywhere for deploying the HcCaffe benchmark? If I can get it automated for PTS, can run a large comparison on many different GPUs.

My current test script for Caffe is http://openbenchmarking.org/innhold/622aa95f22029911b8cfc99e9ddc292d237e8571 if anyone wants to adapt it for HcCaffe as well, patches welcome.
