### ISSUE TITLE
Old TensorFlow version (0.6) is used for benchmarking. 

### ISSUE THREAD

**Issue by MikalaiDrabovich** [soumith/convnet-benchmarks#86]
r0.7 should have much better performance, as it allows using Cuda >= 7.0 and cuDNN R4, besides other improvements.

**Comment by ppwwyyxx** [comment]
For people who're curious, I ran the benchmark for TensorFlow 0.7.0 with cuda7.5 and cudnnR4, on Quadro M6000 (very similar to TitanX). I saw a 20-40% speedup compared to the old numbers in this repo.
For alexnet/vgg where there's a lot more convolution, the speedup is higher. For googlenet it's about 20% only. There is still an obvious gap compared to other libraries with cudnnR3.

**Comment by soumith** [comment]
thanks. i'll run the numbers in a couple of hours.

**Comment by soumith** [comment]
closed via https://github.com/soumith/convnet-benchmarks/commit/2888b23959190cefeee59cdd5e15f66a74031f8f
