### ISSUE TITLE
DNN OpenCV module

### ISSUE THREAD

**Issue by bhack** [soumith/convnet-benchmarks#88]
Are you interested to benchmark [ OpenCV  DNN module](https://github.com/Itseez/opencv_contrib/tree/master/modules/dnn)?

**Comment by soumith** [comment]
i dont mind benchmarking, but i dont have the time to extend convnet-benchmarks to this.
I am working on a bigger fuller benchmark suite that spans all of deep learning, so all my benchmark time is occupied by writing scripts for those.

**Comment by bhack** [comment]
Do you have an idea of when this will be published?

**Comment by soumith** [comment]
Target date is April 1st, around the time of GTC

**Comment by bhack** [comment]
Nice so probably we will put a GSoC student to this new one. Thanks.
