### ISSUE TITLE
benchmark for https://github.com/NVIDIA/caffe

### ISSUE THREAD

**Issue by weishengchong** [soumith/convnet-benchmarks#95]
Hi,

May I have your help on my question in 
https://github.com/NVIDIA/caffe/issues/120

 Googlenet@batch64 for "caffe time" return "killed" #120 
I tried reproducing inference performance results for Tx1 whitepapers on Jetson Tx1 board.

**[experiment setup]**

(a)set GPU frequency as 690MHz and confirmed by tegrastats.
(b)[2] remove backward part in tools/caffe.cpp , without this modification, Alexnet@batch128 return "killed"
I think environment setup is correct because I managed to get similar reading for tables below
(2)table1 Alexnet@Tx1 for fp32 fp16 batch1 batch128
(3)table3 Googlenet@Tx1 for fp32 batch1,
(4)table3 Googlenet@Tx1 for fp16 batch1 batch64,

**[Question]**
I have error below for (1)table3 Googlenet@Tx1 for fp32 batch64

I0108 22:57:14.231255 17916 net.cpp:298] Memory required for data: 3491278848 <-- 3.5GByte
I0108 22:57:14.232288 17916 caffe.cpp:319] Performing Forward
Killed

below is tegrastats result
RAM 1266/3854MB (lfb 413x4MB) SWAP 0/0MB (cached 0MB) cpu [37%,3%,96%,2%]@1912 EMC 4%@1600 AVP 9%@12 VDE 0 GR3D 0%@691 EDP limit 1912
RAM 1479/3854MB (lfb 413x4MB) SWAP 0/0MB (cached 0MB) cpu [2%,2%,100%,2%]@1912 EMC 4%@1600 AVP 2%@12 VDE 0 GR3D 0%@691 EDP limit 1912
...
RAM 1480/3854MB (lfb 413x4MB) SWAP 0/0MB (cached 0MB) cpu [2%,100%,2%,1%]@1912 EMC 0%@1600 AVP 2%@12 VDE 0 GR3D 0%@691 EDP limit 1912
RAM 1024/3854MB (lfb 484x4MB) SWAP 0/0MB (cached 0MB) cpu [9%,59%,12%,13%]@1912 EMC 3%@1600 AVP 23%@12 VDE 0 GR3D 0%@691 EDP limit 1912

Q1: Is above caused by "Memory required for data 3.5GByte " that is overloading 4Gbyte Tx1 board?
Q2: If Q1 is yes, any solutions is much appreciated.

Thank you very much.

[1] Tx1 whitepapers
https://www.nvidia.com/content/tegra/embedded-systems/pdf/jetson_tx1_whitepaper.pdf

[2] tools/caffe.cpp modification

// Time backward layers
//for (int i = layers.size() - 1; i >= 0; --i) {
  //timer.Start();
  //layers[i]->Backward(top_vecs[i], bottom_need_backward[i],
                      //bottom_vecs[i]);
  //backward_time_per_layer[i] += timer.MicroSeconds();
//}

//// Time total backward
//backward_timer.Start();
//for (int i = layers.size() - 1; i >= 0; --i) {
  //layers[i]->Backward(top_vecs[i], bottom_need_backward[i],
                      //bottom_vecs[i]);
//}
//backward_time += backward_timer.MicroSeconds();

Thank you.

**Comment by soumith** [comment]
ask this on nvidia/caffe. wrong repo.

**Comment by tangyibin** [comment]
I got the same situation here. Same prototxt and caffemodel worked well on my server,  but on TX1, killed. 

Maybe the problem comes from the storage space ?
