### ISSUE TITLE
add imagenet winner benchmark for theano

### ISSUE THREAD

**Issue by chasegh** [soumith/convnet-benchmarks#97]
Hi there,
Thanks for making uniform benchmarks for all those DL tools. When comparing performance of alexnet over all these tools, I found that no theano implementation is made.
So I wanna ask is it still a bottleneck for theano to implement alexnet at present?

**Comment by pengzhao-intel** [comment]
FYI, there is a benchmark with Theano for convnet-benchmark.

+1 for integration of Theaon on the table in this repo.

https://github.com/intel/Theano/blob/dev/README.md

**Comment by nouiz** [comment]
There is imagenet Theano benchmark, check in this folder:

https://github.com/soumith/convnet-benchmarks/blob/master/theano/alexnet.py

I just want to point that th URL point to Intel Theano version, that speed
up Theano on CPU. Currently all the benchmark was done on GPU. So this is
another issue. If you are interrested in that, I would suggest you to open
a new issue to run the benchmark on CPU, and make a PR to modify the
current benchmark to run on CPU too. Probably soumith don't have time for
this, so helping him is probably the only way you can get that.

**Comment by chasegh** [comment]
You guys just replied a one-year-ago issue. It's not a problem now. Anyway, thanks for your reply, best wishes!
